apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dice-content-management
  description: Dice Content Management
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: DICE
