apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dice-integration-api
  description: Dice Integration API
  tags:
    - rest
spec:
  type: openapi
  lifecycle: experimental
  owner: team-a
