apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dice-analytics
  description: Dice Analytics
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: DICE
