DROP TABLE IF EXISTS EVT_QRTZ_CALENDARS;
DROP TABLE IF EXISTS EVT_QRTZ_CRON_TRIGGERS;
DROP TABLE IF EXISTS EVT_QRTZ_FIRED_TRIGGERS;
DROP TABLE IF EXISTS EVT_QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE IF EXISTS EVT_QRTZ_SCHEDULER_STATE;
DROP TABLE IF EXISTS EVT_QRTZ_LOCKS;
DROP TABLE IF EXISTS EVT_QRTZ_JOB_DETAILS;
DROP TABLE IF EXISTS EVT_QRTZ_SIMPLE_TRIGGERS;
DROP TABLE IF EXISTS EVT_QRTZ_SIMPROP_TRIGGERS;
DROP TABLE IF EXISTS EVT_QRTZ_BLOB_TRIGGERS;
DROP TABLE IF EXISTS EVT_QRTZ_TRIGGERS;
DROP TABLE IF EXISTS EVT_QRTZ_FIRED_TRIGGERS_BY_INSTANCE;
DROP TABLE IF EXISTS EVT_QRTZ_JOB_DETAILS_BY_JOB;
DROP TABLE IF EXISTS EVT_QRTZ_CRON_TRIGGERS_BY_TRIGGER;
DROP TABLE IF EXISTS EVT_QRTZ_SIMPLE_TRIGGERS_BY_TRIGGER;
DROP TABLE IF EXISTS EVT_QRTZ_TRIGGERS_BY_TRIGGER;


CREATE TABLE IF NOT EXISTS EVT_QRTZ_CALENDARS (
  SCHED_NAME TEXT,
  CALENDAR_NAME TEXT,
  CALENDAR BLOB,
  PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_CRON_TRIGGERS (
  SCHED_NAME TEXT,
  TRIGGER_NAME TEXT,
  TRIGGER_GROUP TEXT,
  CRON_EXPRESSION TEXT,
  TIME_ZONE_ID TEXT,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_FIRED_TRIGGERS (
  SCHED_NAME TEXT,
  ENTRY_ID TEXT,
  TRIGGER_NAME TEXT,
  TRIGGER_GROUP TEXT,
  INSTANCE_NAME TEXT,
  FIRED_TIME BIGINT,
  SCHED_TIME BIGINT,
  PRIORITY INT,
  STATE TEXT,
  JOB_NAME TEXT,
  JOB_GROUP TEXT,
  IS_NONCONCURRENT BOOLEAN,
  REQUESTS_RECOVERY BOOLEAN,
  PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_PAUSED_TRIGGER_GRPS (
  SCHED_NAME TEXT,
  TRIGGER_GROUP TEXT,
  PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_SCHEDULER_STATE (
  SCHED_NAME TEXT,
  INSTANCE_NAME TEXT,
  LAST_CHECKIN_TIME BIGINT,
  CHECKIN_INTERVAL BIGINT,
  PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_LOCKS (
  SCHED_NAME TEXT,
  LOCK_NAME TEXT,
  PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_JOB_DETAILS (
  SCHED_NAME TEXT,
  JOB_NAME TEXT,
  JOB_GROUP TEXT,
  DESCRIPTION TEXT,
  JOB_CLASS_NAME TEXT,
  IS_DURABLE BOOLEAN,
  IS_NONCONCURRENT BOOLEAN,
  IS_UPDATE_DATA BOOLEAN,
  REQUESTS_RECOVERY BOOLEAN,
  JOB_DATA BLOB,
  PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_SIMPLE_TRIGGERS (
  SCHED_NAME TEXT,
  TRIGGER_NAME TEXT,
  TRIGGER_GROUP TEXT,
  REPEAT_COUNT BIGINT,
  REPEAT_INTERVAL BIGINT,
  TIMES_TRIGGERED BIGINT,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_SIMPROP_TRIGGERS (
  SCHED_NAME TEXT,
  TRIGGER_NAME TEXT,
  TRIGGER_GROUP TEXT,
  STR_PROP_1 TEXT,
  STR_PROP_2 TEXT,
  STR_PROP_3 TEXT,
  INT_PROP_1 INT,
  INT_PROP_2 INT,
  LONG_PROP_1 BIGINT,
  LONG_PROP_2 BIGINT,
  DEC_PROP_1 DECIMAL(13,4),
  DEC_PROP_2 DECIMAL(13,4),
  BOOL_PROP_1 BOOLEAN,
  BOOL_PROP_2 BOOLEAN,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_BLOB_TRIGGERS (
  SCHED_NAME TEXT,
  TRIGGER_NAME TEXT,
  TRIGGER_GROUP TEXT,
  BLOB_DATA BLOB,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_TRIGGERS (
  SCHED_NAME TEXT,
  TRIGGER_NAME TEXT,
  TRIGGER_GROUP TEXT,
  JOB_NAME TEXT,
  JOB_GROUP TEXT,
  DESCRIPTION TEXT,
  NEXT_FIRE_TIME BIGINT,
  PREV_FIRE_TIME BIGINT,
  PRIORITY INT,
  TRIGGER_STATE TEXT,
  TRIGGER_TYPE TEXT,
  START_TIME BIGINT,
  END_TIME BIGINT,
  CALENDAR_NAME TEXT,
  MISFIRE_INSTR SMALLINT,
  JOB_DATA BLOB,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_FIRED_TRIGGERS_BY_INSTANCE (
  INSTANCE_NAME TEXT,
  SCHED_NAME TEXT,
  ENTRY_ID TEXT,
  PRIMARY KEY (INSTANCE_NAME, SCHED_NAME, ENTRY_ID)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_JOB_DETAILS_BY_JOB (
  JOB_NAME TEXT,
  JOB_GROUP TEXT,
  SCHED_NAME TEXT,
  DESCRIPTION TEXT,
  JOB_CLASS_NAME TEXT,
  IS_DURABLE BOOLEAN,
  IS_NONCONCURRENT BOOLEAN,
  IS_UPDATE_DATA BOOLEAN,
  REQUESTS_RECOVERY BOOLEAN,
  JOB_DATA BLOB,
  PRIMARY KEY (JOB_NAME, JOB_GROUP, SCHED_NAME)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_CRON_TRIGGERS_BY_TRIGGER (
  TRIGGER_NAME TEXT,
  TRIGGER_GROUP TEXT,
  SCHED_NAME TEXT,
  CRON_EXPRESSION TEXT,
  TIME_ZONE_ID TEXT,
  PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP, SCHED_NAME)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_SIMPLE_TRIGGERS_BY_TRIGGER (
  TRIGGER_NAME TEXT,
  TRIGGER_GROUP TEXT,
  SCHED_NAME TEXT,
  REPEAT_COUNT BIGINT,
  REPEAT_INTERVAL BIGINT,
  TIMES_TRIGGERED BIGINT,
  PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP, SCHED_NAME)
);

CREATE TABLE IF NOT EXISTS EVT_QRTZ_TRIGGERS_BY_TRIGGER (
  TRIGGER_NAME TEXT,
  TRIGGER_GROUP TEXT,
  SCHED_NAME TEXT,
  JOB_NAME TEXT,
  JOB_GROUP TEXT,
  DESCRIPTION TEXT,
  NEXT_FIRE_TIME BIGINT,
  PREV_FIRE_TIME BIGINT,
  PRIORITY INT,
  TRIGGER_STATE TEXT,
  TRIGGER_TYPE TEXT,
  START_TIME BIGINT,
  END_TIME BIGINT,
  CALENDAR_NAME TEXT,
  MISFIRE_INSTR SMALLINT,
  JOB_DATA BLOB,
  PRIMARY KEY (TRIGGER_NAME, TRIGGER_GROUP, SCHED_NAME)
);


